### ISSUE TITLE
RuntimeError: scatter(): Expected dtype int64 for index

### ISSUE THREAD

**Issue by dnlkch** [orbital-materials/orb-models#22]
Hi,

I was trying to run the examples from the README, but encountered the following error:

```
Traceback (most recent call last):
  File "tutorial_example2.py", line 15, in <module>
    result = orbff.predict(graph)
             ^^^^^^^^^^^^^^^^^^^^
  File ".conda\Lib\site-packages\orb_models\forcefield\graph_regressor.py", line 488, in predict
    batch = self.model(batch)
            ^^^^^^^^^^^^^^^^^
  File ".conda\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".conda\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".conda\Lib\site-packages\orb_models\forcefield\gns.py", line 428, in forward  
    batch = gnn(batch)
            ^^^^^^^^^^
  File ".conda\Lib\site-packages\torch\nn\modules\module.py", line 1511, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".conda\Lib\site-packages\torch\nn\modules\module.py", line 1520, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".conda\Lib\site-packages\orb_models\forcefield\gns.py", line 260, in forward  
    receive_attn = segment_ops.segment_softmax(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".conda\Lib\site-packages\orb_models\forcefield\segment_ops.py", line 87, in segment_softmax
    data_max = segment_max(data, segment_ids, num_segments)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".conda\Lib\site-packages\orb_models\forcefield\segment_ops.py", line 63, in segment_max
    return scatter_max(data, segment_ids, dim=0, dim_size=num_segments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".conda\Lib\site-packages\orb_models\forcefield\segment_ops.py", line 291, in scatter_max
    result = result.scatter_reduce(
             ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: scatter(): Expected dtype int64 for index
```

Do you have any suggestion what could cause this behaviour? Thank you very much!

**Comment by benrhodes26** [comment]
Hi there,

I was unable to reproduce this issue. Did you find a resolution?

I wonder if you are globally setting the dtype with `torch.set_default_dtype` somewhere? I have previously found other models like MACE will set global defaults in this way.

**Comment by dnlkch** [comment]
Thank you very much for your reply and the suggestion. It seems the issue may have been related to running it via VS Code on Windows, everything works just fine on Linux.

**Comment by benrhodes26** [comment]
Great!

**Comment by Camgur** [comment]
I ran into the same issue, also in VSCode, also on Windows. 

```
Traceback (most recent call last):
  File "c:\Users\camgu\Goward\Code\MACE\tests\opt_orb.py", line 32, in <module>
    opt.run(fmax=1e-5, steps=400)
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\ase\optimize\optimize.py", line 430, in run
    return Dynamics.run(self, steps=steps)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\ase\optimize\optimize.py", line 275, in run
    for converged in Dynamics.irun(self, steps=steps):
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\ase\optimize\optimize.py", line 225, in irun
    self.optimizable.get_forces()
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\ase\optimize\optimize.py", line 34, in get_forces
    return self.atoms.get_forces()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\ase\atoms.py", line 812, in get_forces
    forces = self._calc.get_forces(self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\ase\calculators\abc.py", line 30, in get_forces
    return self.get_property('forces', atoms)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\ase\calculators\calculator.py", line 538, in get_property
    self.calculate(atoms, [name], system_changes)
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\orb_models\forcefield\calculator.py", line 77, in calculate
    out = self.model.predict(batch)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\orb_models\forcefield\graph_regressor.py", line 508, in predict
    batch = self.model(batch)
            ^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\orb_models\forcefield\gns.py", line 481, in forward
    batch = gnn(batch)
            ^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\torch\nn\modules\module.py", line 1736, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\torch\nn\modules\module.py", line 1747, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\orb_models\forcefield\gns.py", line 317, in forward
    sent_attributes = segment_ops.segment_sum(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\orb_models\forcefield\segment_ops.py", line 58, in segment_sum
    return scatter_sum(data, segment_ids, dim=0, dim_size=num_segments)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\camgu\Goward\Code\mace-env\Lib\site-packages\orb_models\forcefield\segment_ops.py", line 173, in scatter_sum
    return out.scatter_add_(dim, index, src)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: scatter(): Expected dtype int64 for index
```

Here's the hotfix:

In _segment_ops.py_, change line 173  in scatter_sum to 
`return out.scatter_add_(dim, index.to(torch.int64), src)`

It seems like torch directly passes a torch.Tensor to the index position.
