### ISSUE TITLE
Issues Installing `pynanoflann` on Apple Silicon

### ISSUE THREAD

**Issue by corinwagen** [orbital-materials/orb-models#39]
Hey folks, I encountered some difficulties getting ORB models to run on my 2023 Macbook Pro (Apple Silicon, M3 Pro). I figured I'd document the steps I took, since others might have these same issues and it might be worth making a note in `README.md`.

## Problem

Running: 

```
$ pip install "pynanoflann@git+https://github.com/dwastberg/pynanoflann#egg=af434039ae14bedcbb838a7808924d6689274168",
$ python
>>> import pynanoflann
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/cwagen/micromamba/envs/nnp/lib/python3.12/site-packages/pynanoflann/__init__.py", line 1, in <module>
    from .nanoflann import KDTree, batched_kneighbors
  File "/Users/cwagen/micromamba/envs/nnp/lib/python3.12/site-packages/pynanoflann/nanoflann.py", line 6, in <module>
    from . import nanoflann_ext
ImportError: dlopen(/Users/cwagen/micromamba/envs/nnp/lib/python3.12/site-packages/pynanoflann/nanoflann_ext.cpython-312-darwin.so, 0x0002): tried: '/Users/cwagen/micromamba/envs/nnp/lib/python3.12/site-packages/pynanoflann/nanoflann_ext.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/cwagen/micromamba/envs/nnp/lib/python3.12/site-packages/pynanoflann/nanoflann_ext.cpython-312-darwin.so' (no such file), '/Users/cwagen/micromamba/envs/nnp/lib/python3.12/site-packages/pynanoflann/nanoflann_ext.cpython-312-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
```

## My Solution
(1) Clone `pynanoflann`

```
$ git clone https://github.com/dwastberg/pynanoflann.git
$ cd pynanoflann
```

(2) Modify their `CMakeLists.txt` file and add the following lines (these became lines 10–13 in the new file):
```
if(APPLE)
    # Ensure compatibility with ARM64 architecture on macOS
    set(CMAKE_OSX_ARCHITECTURES "arm64" CACHE STRING "Build architecture" FORCE)
endif()
```
 
(3) Install the modified version into whatever environment:

```sh
$ pip install .
```

**Comment by timduignan** [comment]
Ah interesting thanks Corin, maybe I avoided this by using python 3.11.

**Comment by corinwagen** [comment]
yep, following these directions worked! I didn't worry about GPU, CPU was fast enough

**Comment by corinwagen** [comment]
I've been a bit miffed about this, since it makes managing our build system significantly more annoying, so I added `pynanoflann` to Pypi

https://pypi.org/project/pynanoflann/

hopefully this helps

**Comment by timduignan** [comment]
Nice thanks Corin!

**Comment by DeNeutoy** [comment]
Ah nice one @corinwagen - we've actually dropped pynannoflann in #61 as we prepare for some new models - now we just require `scipy`, aka much easier. Thanks for making the effort though!

**Comment by corinwagen** [comment]
beautiful
